import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import HeaderMain from "@/components/HeaderMain";
import Navbar from "@/components/Navbar";
import Progressindicator from "@/components/Progressindicator";
import Roundpills from "@/components/Roundpills";
import Bulletpoints from "@/components/Bulletpoints";
import Crosses from "@/components/Crosses";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <HeaderTop/>
        <HeaderMain/>
        <Navbar/> */}
        {/* <Progressindicator />
        <Roundpills />
        <Crosses /> */}
        {children}
        </body>
    </html>
  );
}
